version: 2

jobs:
  build_and_test:

    machine:
      enabled: true
      image: circleci/classic:201808-01

    steps:
      - checkout

      - run:
          name: Fix circleci file permissons
          command: sudo chown ubuntu:ubuntu -R *

      - run:
          name: Prepare local environment file
          command: |
            make prepare
            # The project setup is Mac by default, so we need to change to Linux image.
            # Uncomment all the strings containing `PHP_TAG`.
            sed -i '/PHP_TAG/s/^# //g' \.env
            # Comment all the strings containing `-dev-macos-`.
            sed -i '/-dev-macos-/s/^/# /g' \.env

      - run:
          name: Make local environment
          command: make install
          no_output_timeout: 20m

      - run:
          name: Check Drupal & React.js code for compliance with coding standards
          command: make code:check
          when: always

      #- run:
      #    name: Add hosts into /etc/hosts
      #    command: echo 127.0.0.1 app.docker.localhost drupal.docker.localhost | sudo tee -a /etc/hosts

      - run:
          name: Run Unit (integration) tests
          command: make tests:run unit

      - run:
          name: Run API tests
          command: make tests:run api

      - run:
          name: Run Acceptance tests
          command: make tests:run acceptance

      - store_artifacts:
          path: tests/_output

workflows:
  version: 2

  build_and_test:
    jobs:
      - build_and_test
